modLoader="javafml"
loaderVersion="[33,)"
license="GPLv3"
[[mods]]
modId="auudio"
version="1.0.3"
displayName="Auudio"
authors="Keksuccino"
description='''
Library to play background sounds in menus and worlds.

COPYRIGHT:

> Auudio © Copyright 2022 Keksuccino.
  Auudio is licensed under GPLv3.
'''

[[dependencies.auudio]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="CLIENT"

[[dependencies.auudio]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2,)"
ordering="NONE"
side="CLIENT"